### ISSUE TITLE
Stereo music sources not running in direct channel mode

### ISSUE THREAD

**Issue by nickbrowne** [jhasse/ears#19]
It seems like openal-soft 1.17 added a new algorithm to "spread" stereo sources across multiple channels, which is colouring the sound even with only 2 channels (headphones). This doesn't sound great when you are attempting to play music produced and mixed for stereo.

One option is to disable HRTF all together, but that's not ideal because HRTF is actually great for everything else! Another is to configure specific sources to run in direct channel mode.

Considering that ears seems intended to be an easy way to get sensible behaviour out of OpenAL, I think most people would expect all music sources to run in direct channel mode.

Another alternative would be to add it as configurable option for music sources: 
```rust
music.set_direct_channel(true);
```

But I'm not sure... Do you have any opinions on the best way to provide this feature?

I've been using this branch to fix the problem for myself, but it's likely something others would want too:
https://github.com/jhasse/ears/compare/master...nickbrowne:prefer-direct-channel-music

If you're happy with my solution I'll gladly pull request it.

More info on direct channels here:
https://github.com/openalext/openalext/blob/master/AL_SOFT_direct_channels.txt

**Comment by jhasse** [comment]
> It seems like openal-soft 1.17 added a new algorithm to "spread" stereo sources across multiple channels, which is colouring the sound even with only 2 channels (headphones). This doesn't sound great when you are attempting to play music produced and mixed for stereo.

Why are they doing this?

**Comment by nickbrowne** [comment]
I'll be honest, I'm really not sure, but it seems like an intentional change. Even though to me it goes against the original spec (stereo sources pass through untouched). 

There's a bit of discussion about it here
http://openal.org/pipermail/openal/2017-February/000604.html
and a semi related issue here
https://github.com/kcat/openal-soft/issues/72

**Comment by nickbrowne** [comment]
Here are some recordings from the music example to demonstrate the issue:
 - current master: https://slack-files.com/T02DTH8FG-F9S1CE2PK-48f63055fd
 - my branch with source in direct channel mode: https://slack-files.com/T02DTH8FG-F9SGPTD3N-978ee44554

I can't say that current master is "bad", but it just doesn't sound like our composer intended.

**Comment by jhasse** [comment]
It sounds to me that the direct channel mode might be bad for some x.1 systems, because the subwoofer won't work correctly then? @kcat probably understands it better than me and can elaborate?

**Comment by nickbrowne** [comment]
Right, it is quite possible that I've misunderstood the purpose of direct channel mode, even though it's giving me the desired effect.

**Comment by kcat** [comment]
> It seems like openal-soft 1.17 added a new algorithm to "spread" stereo sources across multiple channels, which is colouring the sound even with only 2 channels (headphones).

These are actually two separate things. The new panning algorithm in 1.17 is an ambisonic-based panner for surround sound speakers (it's also kind of used with plain stereo, though it's done in a way to make it act more like normal pair-wise mixing with a front stage of -30 to +30 degrees, as is normal for stereo speakers). The coloring that occurs with headphones is because stereo sounds also pass through HRTF, to make it act as if it's playing on virtual stereo speakers (this helps keep the sound consistent regardless if the user is using stereo speakers or headphones, and helps ensure the volume of stereo sounds are correct relative to mono and other formats).

If the stereo track is already a binaural mix, the direct_channels extension allows it to bypass virtualization. The main caveat with that extension is that it fails with mono or B-Format output since they have no front-left and front-right speakers (not typically used, but still worth mentioning). An alternative is to use the `AL_EXT_STEREO_ANGLES` extension to set the stereo channels to the immediate left and right, so that it's a wider response than the default 60-degree stereo image.

> It sounds to me that the direct channel mode might be bad for some x.1 systems, because the subwoofer won't work correctly then?

When playing a stereo sound (or mono, quad, B-Format) over x.1 systems, any response from the sub-woofer is generated by the speakers themselves. OpenAL Soft doesn't do anything with the LFE/subwoofer unless using a buffer format or effect that explicitly handles LFE. Turning on direct channels shouldn't have any serious effect on the sub-woofer, though depending on how exactly a given subwoofer works, it may pick up a bit more or less bass compared to the normal panned channel responses.

**Comment by nickbrowne** [comment]
Thanks for the detail (and your hard work on OpenAL Soft!), very useful to have an understanding of what's going on here.

Knowing this, it does sound more appropriate to go with my other suggestion to add a method on `Music` to allow people configure the source to output direct channel mode if they would prefer it.

Something like:
```rust
music.set_direct_channel(true);
```

Does that sound sensible to you @jhasse? If so I'm happy to open a pull request to add that feature if it's something you think will be useful to others as well.

**Comment by jhasse** [comment]
Yes, sounds good :)
